apiVersion: v1
kind: Service
metadata:
  name: "orderqueryms-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 9080
  - name: https
    port: 9443

  selector:
    app: "orderqueryms-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "orderqueryms-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "orderqueryms-selector"
    spec:
      containers:
      - name: orderqueryms
        image: orderqueryms:latest
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 20
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
