{{- if .Values.route.enabled -}}
{{- $routePath := .Values.route.path -}}
{{- $chartName := .Chart.Name -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  #TODO Add default name overrides?
  name: {{ .Values.route.urlPrefix }}
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/part-of: refarch-kc
spec:
  path: {{ $routePath }}
  to:
    kind: Service
    name: "order-query-ms"
    weight: 100
  port:
    targetPort: http
{{- end }}
